# App
spring.application.name=task-manager
server.port=8080

# Database - MySQL
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/taskManagerNew?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
app.jwt.secret=${JWT_SECRET:mySecretKey123456789012345678901234567890AbcDef}
app.jwt.expiration=86400000